### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by refi64** [mortie/mortup-js#1]
Nice project! However, IMO, syntax highlight is a must where code blocks are involved. Could this be added?

**Comment by mortie** [comment]
It would be rather hard, and imo out of the scope of this project, to add syntax highlighting. However, I have thought about adding a way to specify the language of a code block, which would allow you to add a third party syntax highlighter.

Something like:

``````
``` javascript
    console.log("I am javascript");
```
``````

could produce:

```
<pre><code data-language="javascript">
    console.log("I am javascript");
</code></pre>
```

**Comment by mortie** [comment]
I added that feature just now: https://github.com/mortie/mortup-js/commit/0ffcd26b86d3a55ff2d42c33a4a65fd5747392de
